export const countryCodes = [
  { name: "Egypt", code: "+20", flag: '🏳️‍🌈' },
  { name: "Saudi Arabia", code: "+966", flag: "SA" },
  { name: "United Arab Emirates", code: "+971", flag: "AE" },
  { name: "Qatar", code: "+974", flag: "QA" },
  { name: "Kuwait", code: "+965", flag: "KW" },
  { name: "Bahrain", code: "+973", flag: "🇧🇭" },
  { name: "Oman", code: "+968", flag: "🇴🇲" },
  { name: "Jordan", code: "+962", flag: "🇯🇴" },
  { name: "Lebanon", code: "+961", flag: "🇱🇧" },
  { name: "Morocco", code: "+212", flag: "🇲🇦" },
  { name: "Algeria", code: "+213", flag: "🇩🇿" },
  { name: "Tunisia", code: "+216", flag: "🇹🇳" },
  { name: "Libya", code: "+218", flag: "🇱🇾" },
  { name: "Sudan", code: "+249", flag: "🇸🇩" },
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "Italy", code: "+39", flag: "🇮🇹" },
  { name: "Spain", code: "+34", flag: "🇪🇸" },
];
